### ISSUE TITLE
UDP Datagram

### ISSUE THREAD

**Issue by googols** [ignacio/LuaNode#26]
I have spent most of the morning attempting to get the remote address and port to display properly in datagram.lua.  

Love the project, and I would love to use it, if i could just identify where the packet originated (the equivalent of rinfo in nodejs).

Any suggestions welome.

**Comment by ignacio** [comment]
Hi. UDP is not implemented at the moment. I mean, there is some code there that exposes part of  Asio, but I have no tests, no examples and more importantly, no idea how to use UDP since I never wrote anything that used it.
Sadly, I can't devote any time to add udp support right now.
However, a pull request would be nice.

I would look into Boost Asio documentation and in node.js tests regarding udp, to see what needs to be done.

I'm sorry I can't be of any help at the moment. :(

**Comment by googols** [comment]
Not to worry. Many thanks for the follow up (I too have no idea how to implement such things either).  I will consult a higher programming power, and if I can find anything useful I will let you know.

Thank you.
